// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckMatch(ctx context.Context, arg CheckMatchParams) (bool, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (sql.Result, error)
	CreateSwipe(ctx context.Context, arg CreateSwipeParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetMatches(ctx context.Context, arg GetMatchesParams) ([]Match, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
