// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckMatch(ctx context.Context, arg CheckMatchParams) (bool, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (sql.Result, error)
	CreateRanking(ctx context.Context, userID string) (sql.Result, error)
	CreateSwipe(ctx context.Context, arg CreateSwipeParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DiscoverUsersV1(ctx context.Context, arg DiscoverUsersV1Params) ([]DiscoverUsersV1Row, error)
	DiscoverUsersV2(ctx context.Context, arg DiscoverUsersV2Params) ([]DiscoverUsersV2Row, error)
	GetMatches(ctx context.Context, arg GetMatchesParams) ([]Match, error)
	GetRankingByUserId(ctx context.Context, userID string) (Ranking, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, userID string) (User, error)
	UpdateRanking(ctx context.Context, arg UpdateRankingParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
