// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ranking.sql

package db

import (
	"context"
	"database/sql"
)

const createRanking = `-- name: CreateRanking :execresult
INSERT INTO Rankings (user_id, like_count, dislike_count, attractiveness_score)
VALUES (?, 0, 0, 0.0)
`

func (q *Queries) CreateRanking(ctx context.Context, userID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRanking, userID)
}
