// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO Users (user_id, email, password, name, gender, age, latitude, longitude, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateUserParams struct {
	UserID    string  `json:"user_id"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Name      string  `json:"name"`
	Gender    string  `json:"gender"`
	Age       int32   `json:"age"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Gender,
		arg.Age,
		arg.Latitude,
		arg.Longitude,
	)
}

const discoverUsersV1 = `-- name: DiscoverUsersV1 :many
SELECT user_id, name, gender, age
FROM Users
WHERE user_id NOT IN (
    SELECT swipee_id
    FROM Swipes
    WHERE swiper_id = ?
)
AND user_id != ?
`

type DiscoverUsersV1Params struct {
	SwiperID string `json:"swiper_id"`
	UserID   string `json:"user_id"`
}

type DiscoverUsersV1Row struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
	Age    int32  `json:"age"`
}

func (q *Queries) DiscoverUsersV1(ctx context.Context, arg DiscoverUsersV1Params) ([]DiscoverUsersV1Row, error) {
	rows, err := q.db.QueryContext(ctx, discoverUsersV1, arg.SwiperID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverUsersV1Row{}
	for rows.Next() {
		var i DiscoverUsersV1Row
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Gender,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const discoverUsersV2 = `-- name: DiscoverUsersV2 :many
SELECT u.user_id, u.name, u.gender, u.age, u.latitude, u.longitude, r.attractiveness_score
FROM Users u
LEFT JOIN Rankings r ON u.user_id = r.user_id
WHERE u.user_id NOT IN (
    SELECT swipee_id
    FROM Swipes
    WHERE swiper_id = ?
) 
AND u.user_id != ?
AND u.age >= COALESCE(?, u.age)
AND u.age <= COALESCE(?, u.age)
AND u.gender = COALESCE(?, u.gender)
ORDER BY r.attractiveness_score DESC
`

type DiscoverUsersV2Params struct {
	SwiperID       string         `json:"swiper_id"`
	UserID         string         `json:"user_id"`
	GreaterThanAge sql.NullInt32  `json:"greater_than_age"`
	LowerThanAge   sql.NullInt32  `json:"lower_than_age"`
	Gender         sql.NullString `json:"gender"`
}

type DiscoverUsersV2Row struct {
	UserID              string          `json:"user_id"`
	Name                string          `json:"name"`
	Gender              string          `json:"gender"`
	Age                 int32           `json:"age"`
	Latitude            float64         `json:"latitude"`
	Longitude           float64         `json:"longitude"`
	AttractivenessScore sql.NullFloat64 `json:"attractiveness_score"`
}

func (q *Queries) DiscoverUsersV2(ctx context.Context, arg DiscoverUsersV2Params) ([]DiscoverUsersV2Row, error) {
	rows, err := q.db.QueryContext(ctx, discoverUsersV2,
		arg.SwiperID,
		arg.UserID,
		arg.GreaterThanAge,
		arg.LowerThanAge,
		arg.Gender,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscoverUsersV2Row{}
	for rows.Next() {
		var i DiscoverUsersV2Row
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Gender,
			&i.Age,
			&i.Latitude,
			&i.Longitude,
			&i.AttractivenessScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password, name, gender, age, latitude, longitude, created_at, updated_at
FROM Users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Gender,
		&i.Age,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, email, password, name, gender, age, latitude, longitude, created_at, updated_at
FROM Users
WHERE user_id = ?
`

func (q *Queries) GetUserById(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Gender,
		&i.Age,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
